runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /vendor
  static_dir: vendor

- url: /data
  script: main.app


- url: /chartist
  static_dir: bower_components/chartist/dist

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest


